dist: xenial
language: python
python: 3.7

install:
  - pip install flake8 kodi-addon-checker git+https://github.com/romanvm/kodi-addon-submitter.git

before_script:
- git config core.quotepath false

# command to run our tests
script:
  - flake8 ./ --statistics --show-source --builtins=sys --ignore=E501,E722 --exclude=croniter.py # check python structure against flake8 tests, ignore long lines
  - kodi-addon-checker --branch=matrix --allow-folder-id-mismatch
  
deploy:
  - provider: script
    script: submit-addon -r repo-plugins -b matrix --push-branch script.xbmcbackup
    on:
      tags: true